### ISSUE TITLE
After upgrade to v3.3.0

### ISSUE THREAD

**Issue by thvd** [hultenvp/solis-sensor#253]
With version 3.2.1 everything was working fine. But after upgrading to v3.3.0 my install broke.

Error message from HA logs:

> Setup failed for custom integration solis: Unable to import component: cannot import name 'SoliscloudConfig' from 'custom_components.solis.soliscloud_api' (/config/custom_components/solis/soliscloud_api.py)

**Comment by thvd** [comment]
By bad. Not all files properly updated.
